version: '3.1'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root 
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
  
  redis:
    image: redis:6.0.1-alpine
    ports:
      - 6379:6379